set t_Co=256
set nocp
set encoding=utf-8

set softtabstop=4
set tabstop=4
set expandtab
set shiftwidth=4
set autoindent
set hidden	    "buffers keep change history
set scrolloff=3	    "keep 3 lines below and above cursor

" ignores
set wildignore+=virtualenv/**,node_modules/**,static/js/lib/**

" filetype plugins
filetype on
filetype plugin on
filetype plugin indent on

" Display
set number
:syntax on
set background=dark
colorscheme BusyBee
set foldmethod=indent
set foldlevel=100
set nowrap
set hlsearch
set cursorline

" Autocomplete features in the status bar
set wildmenu

"""" statusline
"set statusline=%t[%{strlen(&fenc)?&fenc:'none'},%{&ff}]%h%m%r%y%=%c,%l/%L\ %P\ %{fugitive#statusline()}
set laststatus=2

"""" Paste mode toggle
nnoremap <F2> :set invpaste paste?<CR>
set pastetoggle=<F2>
set showmode

"""" Djagno snippets
"autocmd FileType python set ft=python.django
autocmd FileType html set ft=htmldjango.html

"""" Powerline
"let g:Powerline_cache_dir = simplify(expand('<sfile>:p:h') .'/..')
let g:Powerline_symbols = 'fancy'
let g:Powerline_theme = 'default'
let g:Powerline_colorscheme = 'solarized256'
let g:Powerline_stl_path_style = 'relative'

"""" PySmell
"autocmd FileType python setlocal omnifunc=pysmell#Complete

"""" MiniBufExplorer
let g:miniBufExplMapWindowNavVim = 1
let g:miniBufExplMapWindowNavArrows = 1
let g:miniBufExplMapCTabSwitchBufs = 1
let g:miniBufExplModSelTarget = 1 

"""" SuperTab
let g:SuperTabDefaultCompletionType = 'context'
"let g:SuperTabDefaultCompletionType = "<C-x><C-o>"

"""" completion menu tweaks
set completeopt=longest,menuone

"""" TagList
let Tlist_WinWidth = 50
let Tlist_Exit_OnlyWindow = 1
let Tlist_GainFocus_On_ToggleOpen = 1
let Tlist_File_Fold_Auto_Close = 1
let Tlist_Close_On_Select = 1
let Tlist_Sort_Type = 'name'
"map P :TlistToggle<CR>
map <leader>t :TlistToggle<CR>

"""" Command-T
map <leader>c :CommandT<CR>

"""" TaskList
"map T :TaskList<CR>

"""" NERDTree
let NERDTreeQuitOnOpen = 1
let NERDTreeWinSize = 50
let NERDTreeIgnore=['\.pyc$', '\.vim$', '\~$']
map <leader>N :NERDTreeToggle<CR>
"map ob :NERDTreeFromBookmark 

"""" Rope
map <leader>j :RopeGotoDefinition<CR>
map <leader>r :RopeRename<CR>

"""" BufExplorer
"map <leader>b :BufExplorer<CR>

"""" Key Mappings
" bind ctrl+space for omnicompletion
inoremap <Nul> <C-x><C-o>
" Code folding toggle
nmap <CR> za 
" git diff
nnoremap <silent> <F10> :w<CR>:!git diff %<CR>
" zsh
nnoremap <silent> <F3> :w<CR>:!zsh<CR>
" ranger
nnoremap <silent> <F4> :w<CR>:!ranger<CR>
" window sizing
map <silent> <A-h> <C-W><
map <silent> <A-j> <C-W>-
map <silent> <A-k> <C-W>+
map <silent> <A-l> <C-W>>

"""" Trac Servers
let g:tracServerList = {}
" let g:tracServerList['(Server Name)'] = 'http://(user):(password)@(trac serverpath)/login/xmlrpc' 

call pathogen#infect()

"""" VirtualEnv
py << EOF
import os
import sys
import vim
project_base_dir = None
if 'virtualenv' in os.listdir('.'):
    project_base_dir = os.path.join(os.path.abspath('.'), 'virtualenv')
elif 'VIRTUAL_ENV' in os.environ:
    project_base_dir = os.environ['VIRTUAL_ENV']
if project_base_dir:
    sys.path.insert(0, project_base_dir)
    activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
    execfile(activate_this, dict(__file__=activate_this))
EOF

