#!/usr/bin/zsh -f

pkill feh

[[ -e /tmp/setting-album-art ]] && rm /tmp/setting-album-art && exit 1

touch /tmp/setting-album-art

music_dir=/copy/Copy/music

album="$(mpc -f %album% current)"
file="$(mpc -f %file% current)"
album_dir="${file%/*}"
[[ -z "$album_dir" ]] && echo 'album_dir is empty' && exit 1
album_dir="$music_dir/$album_dir"

art="$(find "$album_dir" -type d -exec find {} -maxdepth 1 -type f -iregex ".*/.*\(${album}\|cover\|folder\|artwork\|front\).*[.]\(jpe?g\|png\|gif\|bmp\)" \;)"
echo -e $art > /tmp/album-art-path

[[ ! -s /tmp/album-art-path ]] && echo 'album-art-path file is empty' && exit 1

cat "$(cat /tmp/album-art-path)" | feh -Z -g 100x100 -B black -^ album-art - &
